inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.5

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/StringLiterals:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'test/examples/*_doc.rb'

Layout/AlignParameters:
  Enabled: false
