inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-minitest

# Common configuration.
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false


Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'test/examples/*_doc.rb'


Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'test/**/*.rb'

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/ErbNewArguments:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'test/**/*.rb'


Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 500

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 15


Minitest/AssertInDelta:
  Enabled: false

Minitest/AssertTruthy:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false


Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false


Performance/Squeeze:
  Enabled: false


Style/AccessorGrouping:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/GuardClause:
  Enabled: false

Style/HashLikeCase:
  Exclude:
    - 'test/**/*.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
