inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*.rb'

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Naming/HeredocDelimiterNaming:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'test/examples/*_doc.rb'
