inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-minitest

# Common configuration.
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - '_ignore/**/*'
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineContinuationSpacing:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'test/examples/*_doc.rb'

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'test/**/*.rb'

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/ErbNewArguments:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'test/**/*.rb'

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 500

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 15

Minitest/AssertInDelta:
  Enabled: false

Minitest/AssertOperator:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false

Minitest/AssertTruthy:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Minitest/RefuteOperator:
  Enabled: false

Minitest/RefutePredicate:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/VariableNumber:
  Enabled: false


Style/AccessorGrouping:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/examples/*_doc.rb'

Style/GuardClause:
  Enabled: false

Style/HashLikeCase:
  Exclude:
    - 'test/**/*.rb'

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantLineContinuation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SelectByRegexp:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
