sudo: false
language: ruby

cache:
  - bundler

rvm:
  - 2.4.2
  - 2.5.0

env:
  matrix:
    - BUILD_TYPE=default
    - BUILD_TYPE=audit

script:
  - bash ./bin/travis_build.sh

notifications:
  slack: sharesight:U37WSO6VigyXdiL1DOjMCWOO
